### PR TITLE
add mf proxies

### PR DESCRIPTION
**Pull request by nikita-0209**
not been tested yet

UPDATE: testing done

### CODE REVIEW

**Comment by nikita-0209** [comment]
tested with:
```
load_data: True
data_path: "./storage/data_oracle/test_database_fid.npy"
```

**Comment by nikita-0209** [comment]
Remark: we could move the conversion of integer -> one hot encoding conversion of fidelity to `datahandler.preprocess_for_dataloader()`

**Review by alexhernandezgarcia — APPROVED** [review]
I haven't reviewed everything in detail because there is too much code, sorry :(

Generally, it looks like part of code could be reused, especially in the multiple versions of MLP regressive, multi-fidelity, normal, etc.

**Comment by nikita-0209** [comment]
yes, i agree. this is more of a first working version and I think we can update it as we test these proxies in different settings

**Pull request merged**
