### PR TITLE
remove previous code and gfn files

### PR DESCRIPTION
**Pull request by nikita-0209**

### CODE REVIEW

**Comment by nikita-0209** [comment]
and stores the scripts from main-new-al in a separate directory called "main-new-al" (instead of deleting those scripts)

**Review by alexhernandezgarcia — CHANGES_REQUESTED** [review]
I think I would not remove (yet) all the scripts in `previous_code` since some of them might be useful eventually, for example `eval_al.py`. Shall we keep them under version control for now?

**Comment by nikita-0209** [comment]
Oh yeah cool, I'll restore those files.

**Review by alexhernandezgarcia — APPROVED** [review]
ok

**Pull request merged**
